server:
  port: 7000

moose:
  config:
    nacos:
      hostname: 127.0.0.1
      port: 8848

# 配置日志级别，方别调试
logging:
  level:
    org.springframework.cloud.gateway: debug

spring:
  application:
    name: business-gateway-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: ${moose.config.nacos.hostname}:${moose.config.nacos.port}
    # 路由网关配置
    gateway:
      # 设置与服务注册发现组件结合，这样可以采用服务名的路由策略
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        # 采用自定义路由 ID（有固定用法，不同的 id 有不同的功能，详见：https://cloud.spring.io/spring-cloud-gateway/2.0.x/single/spring-cloud-gateway.html#gateway-route-filters）
        - id: BUSINESS-OAUTH2-SERVICE
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://business-oauth2-service
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # 路径匹配，以 api 开头，直接配置是不生效的，看 filters 配置
            - Path=/api/oauth/**
          filters:
            # 前缀过滤，默认配置下，我们的请求路径是 http://localhost:7000/xxxxxx/** 这时会路由到指定的服务
            # 此处配置去掉 1 个路径前缀，再配置上面的 Path=/api/**，就能按照 http://localhost:7000/api/** 的方式访问了
            - StripPrefix=1
        - id: BUSINESS-USER-SERVICE
          uri: lb://business-user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        # 配置 websocket 网关
        - id: BUSINESS-IM-SERVICE
          uri: lb:ws://business-im-service
          predicates:
            - Path=/im/socket.io/**
          filters:
            - StripPrefix=1