server:
  port: 9000

moose:
  config:
    mysql:
      hostname: 127.0.0.1
      port: 3306
    nacos:
      hostname: 127.0.0.1
      port: 8848

spring:
  application:
    name: business-oauth2-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${moose.config.nacos.hostname}:${moose.config.nacos.port}

  datasource:
    name: oauth_service
    url: jdbc:mysql://${moose.config.mysql.hostname}:${moose.config.mysql.port}/oauth_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: business-oauth2-service-dubbo
  scan:
    base-packages: org.moose.business.oauth.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${moose.config.nacos.hostname}
    port: ${moose.config.nacos.port}
    check: false
  consumer:
    check: false

# feign client 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
#  sentinel:
#    enabled: true
  client:
   config:
     default:
       connectTimeout: 10000
       readTimeout: 600000

hystrix:
 command:
   default:  #default全局有效，service id指定应用有效
     execution:
       timeout:
         #如果enabled设置为false，则请求超时交给ribbon控制,为true,否则超时作为熔断根据
         enabled: true
       isolation:
         strategy: SEMAPHORE
         thread:
           timeoutInMilliseconds: 30000 #断路器超时时间，默认1000ms

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.moose.business.oauth.*: debug
