server:
  port: 80

spring:
  application:
    name: user-web-api
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: user-web-api-dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1
    port: 8848
