spring:
  ## 数据库配置
  datasource:
    name: moose
    url: jdbc:mysql://localhost:3306/moose?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # elasticsearch settings
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300

    mongodb:
      uri: mongodb://127.0.0.1:27017/learn

  redis:
    database: 0
    host: localhost
    port: 6379


# logging settings
logging:
  path: E:/develop/elk/logs

## mybatis settings
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.excel.operator.domain

system:
  security:
    anonymous-urls: /api/v1/account/login,/api/v1/account/register,/api/v1/account/login/status