spring:
  ## 数据库配置
  datasource:
    name: moose
    url: jdbc:mysql://localhost:3306/moose?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8&&useSSL=false
    #    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties:
        druid:
          stat:
            mergeSql: true
            slowSqlMillis: 5000

# elasticsearch settings
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300

    mongodb:
      uri: mongodb://127.0.0.1:27017/learn

  redis:
    database: 0
    host: localhost
    port: 6379


# logging settings
logging:
  path: E:/develop/elk/logs

## mybatis settings
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.excel.operator.entity
