moose:
  config:
    rocketmq:
      host: 127.0.0.1
      port: 9876

spring:
  datasource:
    name: sms_service
    url: jdbc:mysql://127.0.0.1:3306/sms_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

## rocketmq settings
#rocketmq:
#  name-server: ${moose.config.rocketmq.host}:${moose.config.rocketmq.port}
#  producer:
#    group: SEND_SMS_PRODUCER_GROUP
#    send-message-timeout: 50000

#mq:
#  sms:
#    consumer:
#      group: SEND_SMS_CONSUMER_GROUP
#    topic: SEND_SMS_CONSUMER_TOPIC
#    tag: SEND_SMS_TAG

## logging settings
logging:
  file:
    path: /Users/taohua/logs

## mybatis settings
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.moose.provider.sms.model.domain
