# 启用配置文件
spring:
  profiles:
    active: dev


## mybatis settings
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.learn.entity

## mybatis-plus settings
#mybatis-plus:
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: org.learn.entity

# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400
  tokenHead: "Bearer "