server:
  port: 8000

github:
  authorize:
    clientId: 10170cbcb39714ae96a3
    redirectUri: http://moose.com/callback
    scope: user

spring:
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  profiles:
    active: dev

dubbo:
  application:
    name: account-service-dubbo
  scan:
    base-packages: org.moose.account.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1
    port: 8848
