server:
  port: 7000

spring:
  ## 数据库配置
  datasource:
    name: moose
    url: jdbc:mysql://localhost:3306/moose?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8&&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  # elasticsearch settings
  data:
    elasticsearch:
      cluster-name: my-application
      cluster-nodes: localhost:9300

    mongodb:
      host: localhost
      port: 27017
      database: moose

  redis:
    database: 15
#    host: redis.moose.com
    host: localhost
#    password: tRedisW135
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss.SSS
    time-zone: GMT+8
#    defaultPropertyInclusion: non_null   #非空属性才序列化
#    deserialization:
#      FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://moose.com:7000/oauth/token
      user-authorization-uri: http://moose.com:7000/oauth/authorize
    resource:
      token-info-uri: http://moose.com:7000/oauth/check_token

# logging settings
#logging:
#  path: E:/develop/elk/logs

## mybatis settings
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: org.moose.operator.model.domain
