server:
  port: 9001

base:
  config:
    oauth:
      hostname: localhost
      port: 9000
    nacos:
      hostname: localhost
      port: 8848

spring:
  application:
    name: business-user-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

# feign client 配置
feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false
#  hystrix:
#    enabled: true
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      grant-type: password
      access-token-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/token
      user-authorization-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/authorize
    resource:
      token-info-uri: http://${base.config.oauth.hostname}:${base.config.oauth.port}/oauth/check_token

#dubbo:
#  application:
#    name: business-user-service-dubbo
#  protocol:
#    name: dubbo
#    port: -1
#  registry:
#    address: nacos://127.0.0.1
#    port: 8848

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.moose.oauth.feign.*: debug
