server:
  port: 9000

moose:
  config:
    mysql:
      hostname: 127.0.0.1
      port: 3306
    nacos:
      hostname: 127.0.0.1
      port: 8848

spring:
  application:
    name: business-oauth2-service
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: ${moose.config.nacos.hostname}:${moose.config.nacos.port}

  datasource:
    name: oauth_service
    url: jdbc:mysql://${moose.config.mysql.hostname}:${moose.config.mysql.port}/oauth_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: business-oauth2-service-dubbo
  scan:
    base-packages: org.moose.business.oauth.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${moose.config.nacos.hostname}
    port: ${moose.config.nacos.port}

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
