server:
  port: 9000

spring:
  application:
    name: business-oauth2-service
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  datasource:
    name: oauth_service
    url: jdbc:mysql://127.0.0.1:3306/oauth_service?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

dubbo:
  application:
    name: business-oauth2-service-dubbo
  scan:
    base-packages: org.moose.oauth.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1
    port: 8848

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
